log:
  level: info
  file: "/var/log/mosdns/mosdns.log"

data_providers:
  - tag: geosite
    file: ./geosite.dat
    auto_reload: true
  - tag: geoip
    file: ./geoip.dat
    auto_reload: true

plugins:
  # 缓存
  - tag: cache
    type: cache
    args:
      size: 1024

  # 转发至本地服务器的插件
  - tag: forward_cn # 转发至本地服务器的插件
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://1.12.12.12'
          trusted: true
          idle_timeout: 60
          enable_pipeline: true
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - addr: 'tls://120.53.53.53'
          trusted: true
          idle_timeout: 60
          enable_pipeline: true
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - addr: 'tls://223.5.5.5'
          trusted: true
          idle_timeout: 8
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false
        - addr: 'tls://223.6.6.6'
          trusted: true
          idle_timeout: 8
          enable_pipeline: false
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false

  # 转发至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: 'tls://8.8.8.8:853'
          socks5: '192.168.50.248:7890'
          trusted: true
          idle_timeout: 30
          enable_pipeline: true
          enable_http3: false
          max_conns: 2
          insecure_skip_verify: false

  # 匹配本地域名的插件
  - tag: query_is_cn_domain
    type: query_matcher
    args:
      domain:
        - 'essmart.co'
        - 'provider:geosite:cn'
        - "provider:geosite:apple"
        - "provider:geosite:apple-cn"
        - 'provider:geosite:icloud'
        - 'provider:geosite:microsoft'

  # 匹配非本地域名的插件
  - tag: query_is_non_cn_domain
    type: query_matcher
    args:
      domain:
        - 'provider:geosite:geolocation-!cn'

  # 匹配本地 IP 的插件
  - tag: response_has_cn_ip
    type: response_matcher
    args:
      ip:
        - 'provider:geoip:cn'

  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  - tag: main_sequence
    type: sequence
    args:
      exec:
        # 缓存
        - cache

        # 已知的本地域名用本地服务器解析
        - if: query_is_cn_domain
          exec:
            - _prefer_ipv4
            - forward_cn
            - _return

        # 已知的非本地域名用远程服务器解析
        - if: query_is_non_cn_domain
          exec:
            - _prefer_ipv4
            - forward_remote
            - _return

          # 剩下的未知域名用 IP 分流。
          # 这里借助了 `fallback` 工作机制。分流原理请参考 `fallback`
          # 的工作流程。
          # primary 从本地服务器获取应答，丢弃非本地 IP 的结果。
        - primary:
            - _prefer_ipv4
            - forward_cn
            - if: "(! response_has_cn_ip) && [_response_valid_answer]"
              exec:
                - _drop_response
          # secondary 从远程服务器获取应答。
          secondary:
            - _prefer_ipv4
            - forward_remote
          # 这里建议设置成 local 服务器正常延时的 2~5 倍。
          # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
          # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
          # 这时用就采用 remote 的应答。单位: 毫秒。
          fast_fallback: 200

servers:
  - exec: main_sequence
    listeners:
      - protocol: udp
        addr: ":53"
      - protocol: tcp
        addr: ":53"